version: '3.6'
services:
  iris:
   build:
     context: .
     dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 1972
      - 57700:52773
      - 53773
    volumes:
      - ./:/irisdev/app
  
